const ESPN = "https://a.espncdn.com/i/teamlogos";

export const teamLogoMap: Record<string, string> = {
  // NFL
  "Minnesota Vikings": `${ESPN}/nfl/500/min.png`,
  "Green Bay Packers": `${ESPN}/nfl/500/gb.png`,
  "Chicago Bears": `${ESPN}/nfl/500/chi.png`,
  "Detroit Lions": `${ESPN}/nfl/500/det.png`,
  "Kansas City Chiefs": `${ESPN}/nfl/500/kc.png`,
  "Carolina Panthers": `${ESPN}/nfl/500/car.png`,
  "Arizona Cardinals": `${ESPN}/nfl/500/ari.png`,
  "Dallas Cowboys": `${ESPN}/nfl/500/dal.png`,
  "Philadelphia Eagles": `${ESPN}/nfl/500/phi.png`,
  "New York Giants": `${ESPN}/nfl/500/nyg.png`,
  "New York Jets": `${ESPN}/nfl/500/nyj.png`,
  "New England Patriots": `${ESPN}/nfl/500/ne.png`,
  "Buffalo Bills": `${ESPN}/nfl/500/buf.png`,
  "Miami Dolphins": `${ESPN}/nfl/500/mia.png`,
  "Pittsburgh Steelers": `${ESPN}/nfl/500/pit.png`,
  "Baltimore Ravens": `${ESPN}/nfl/500/bal.png`,
  "Cleveland Browns": `${ESPN}/nfl/500/cle.png`,
  "Cincinnati Bengals": `${ESPN}/nfl/500/cin.png`,
  "Houston Texans": `${ESPN}/nfl/500/hou.png`,
  "Indianapolis Colts": `${ESPN}/nfl/500/ind.png`,
  "Jacksonville Jaguars": `${ESPN}/nfl/500/jax.png`,
  "Tennessee Titans": `${ESPN}/nfl/500/ten.png`,
  "Denver Broncos": `${ESPN}/nfl/500/den.png`,
  "Las Vegas Raiders": `${ESPN}/nfl/500/lv.png`,
  "Los Angeles Chargers": `${ESPN}/nfl/500/lac.png`,
  "Seattle Seahawks": `${ESPN}/nfl/500/sea.png`,
  "Los Angeles Rams": `${ESPN}/nfl/500/lar.png`,
  "San Francisco 49ers": `${ESPN}/nfl/500/sf.png`,
  "New Orleans Saints": `${ESPN}/nfl/500/no.png`,
  "Atlanta Falcons": `${ESPN}/nfl/500/atl.png`,
  "Tampa Bay Buccaneers": `${ESPN}/nfl/500/tb.png`,
  "Washington Commanders": `${ESPN}/nfl/500/wsh.png`,

  // MLB
  "Minnesota Twins": `${ESPN}/mlb/500/min.png`,
  "Cleveland Guardians": `${ESPN}/mlb/500/cle.png`,
  "Los Angeles Dodgers": `${ESPN}/mlb/500/lad.png`,
  "Atlanta Braves": `${ESPN}/mlb/500/atl.png`,
  "New York Yankees": `${ESPN}/mlb/500/nyy.png`,
  "Boston Red Sox": `${ESPN}/mlb/500/bos.png`,
  "Philadelphia Phillies": `${ESPN}/mlb/500/phi.png`,
  "Chicago Cubs": `${ESPN}/mlb/500/chc.png`,
  "Chicago White Sox": `${ESPN}/mlb/500/chw.png`,
  "New York Mets": `${ESPN}/mlb/500/nym.png`,
  "San Francisco Giants": `${ESPN}/mlb/500/sf.png`,
  "Houston Astros": `${ESPN}/mlb/500/hou.png`,
  "Seattle Mariners": `${ESPN}/mlb/500/sea.png`,
  "Detroit Tigers": `${ESPN}/mlb/500/det.png`,
  "Toronto Blue Jays": `${ESPN}/mlb/500/tor.png`,
  "Baltimore Orioles": `${ESPN}/mlb/500/bal.png`,
  "Tampa Bay Rays": `${ESPN}/mlb/500/tb.png`,
  "Miami Marlins": `${ESPN}/mlb/500/mia.png`,
  "Milwaukee Brewers": `${ESPN}/mlb/500/mil.png`,
  "St. Louis Cardinals": `${ESPN}/mlb/500/stl.png`,
  "Cincinnati Reds": `${ESPN}/mlb/500/cin.png`,
  "Pittsburgh Pirates": `${ESPN}/mlb/500/pit.png`,
  "Colorado Rockies": `${ESPN}/mlb/500/col.png`,
  "Arizona Diamondbacks": `${ESPN}/mlb/500/ari.png`,
  "San Diego Padres": `${ESPN}/mlb/500/sd.png`,
  "Los Angeles Angels": `${ESPN}/mlb/500/ana.png`,
  "Oakland Athletics": `${ESPN}/mlb/500/oak.png`,
  "Texas Rangers": `${ESPN}/mlb/500/tex.png`,
  "Kansas City Royals": `${ESPN}/mlb/500/kc.png`,

  // NHL
  "Minnesota Wild": `${ESPN}/nhl/500/min.png`,
  "Colorado Avalanche": `${ESPN}/nhl/500/col.png`,
  "Winnipeg Jets": `${ESPN}/nhl/500/wpg.png`,
  "Edmonton Oilers": `${ESPN}/nhl/500/edm.png`,
  "Toronto Maple Leafs": `${ESPN}/nhl/500/tor.png`,
  "Montreal Canadiens": `${ESPN}/nhl/500/mtl.png`,
  "Boston Bruins": `${ESPN}/nhl/500/bos.png`,
  "New York Rangers": `${ESPN}/nhl/500/nyr.png`,
  "Chicago Blackhawks": `${ESPN}/nhl/500/chi.png`,
  "Pittsburgh Penguins": `${ESPN}/nhl/500/pit.png`,
  "Philadelphia Flyers": `${ESPN}/nhl/500/phi.png`,
  "Carolina Hurricanes": `${ESPN}/nhl/500/car.png`,
  "Tampa Bay Lightning": `${ESPN}/nhl/500/tb.png`,
  "Florida Panthers": `${ESPN}/nhl/500/fla.png`,
  "Washington Capitals": `${ESPN}/nhl/500/wsh.png`,
  "Nashville Predators": `${ESPN}/nhl/500/nsh.png`,
  "St. Louis Blues": `${ESPN}/nhl/500/stl.png`,
  "Dallas Stars": `${ESPN}/nhl/500/dal.png`,
  "Anaheim Ducks": `${ESPN}/nhl/500/ana.png`,
  "Los Angeles Kings": `${ESPN}/nhl/500/la.png`,
  "San Jose Sharks": `${ESPN}/nhl/500/sj.png`,
  "Seattle Kraken": `${ESPN}/nhl/500/sea.png`,
  "Vancouver Canucks": `${ESPN}/nhl/500/van.png`,
  "Calgary Flames": `${ESPN}/nhl/500/cgy.png`,
  "Vegas Golden Knights": `${ESPN}/nhl/500/vgk.png`,
  "Ottawa Senators": `${ESPN}/nhl/500/ott.png`,
  "Buffalo Sabres": `${ESPN}/nhl/500/buf.png`,
  "Detroit Red Wings": `${ESPN}/nhl/500/det.png`,
  "New Jersey Devils": `${ESPN}/nhl/500/nj.png`,
  "Columbus Blue Jackets": `${ESPN}/nhl/500/cbj.png`,

  // NBA
  "Minnesota Timberwolves": `${ESPN}/nba/500/min.png`,
  "Denver Nuggets": `${ESPN}/nba/500/den.png`,
  "Los Angeles Lakers": `${ESPN}/nba/500/lal.png`,
  "Boston Celtics": `${ESPN}/nba/500/bos.png`,
  "Golden State Warriors": `${ESPN}/nba/500/gsw.png`,
  "Brooklyn Nets": `${ESPN}/nba/500/bkn.png`,
  "Philadelphia 76ers": `${ESPN}/nba/500/phi.png`,
  "Toronto Raptors": `${ESPN}/nba/500/tor.png`,
  "New York Knicks": `${ESPN}/nba/500/nyk.png`,
  "Indiana Pacers": `${ESPN}/nba/500/ind.png`,
  "Chicago Bulls": `${ESPN}/nba/500/chi.png`,
  "Milwaukee Bucks": `${ESPN}/nba/500/mil.png`,
  "Cleveland Cavaliers": `${ESPN}/nba/500/cle.png`,
  "Detroit Pistons": `${ESPN}/nba/500/det.png`,
  "Charlotte Hornets": `${ESPN}/nba/500/cha.png`,
  "Atlanta Hawks": `${ESPN}/nba/500/atl.png`,
  "Miami Heat": `${ESPN}/nba/500/mia.png`,
  "Orlando Magic": `${ESPN}/nba/500/orl.png`,
  "Washington Wizards": `${ESPN}/nba/500/wsh.png`,
  "New Orleans Pelicans": `${ESPN}/nba/500/no.png`,
  "Memphis Grizzlies": `${ESPN}/nba/500/mem.png`,
  "San Antonio Spurs": `${ESPN}/nba/500/sa.png`,
  "Houston Rockets": `${ESPN}/nba/500/hou.png`,
  "Oklahoma City Thunder": `${ESPN}/nba/500/okc.png`,
  "Dallas Mavericks": `${ESPN}/nba/500/dal.png`,
  "Utah Jazz": `${ESPN}/nba/500/utah.png`,
  "Portland Trail Blazers": `${ESPN}/nba/500/por.png`,
  "Los Angeles Clippers": `${ESPN}/nba/500/lac.png`,
  "Sacramento Kings": `${ESPN}/nba/500/sac.png`,
  "Phoenix Suns": `${ESPN}/nba/500/phx.png`,

  // College (Minnesota Gophers — ESPN NCAA ID 135)
  "University of Minnesota": `${ESPN}/ncaa/500/135.png`,
  "University of Minnesota football": `${ESPN}/ncaa/500/135.png`,
  "University of Minnesota basketball": `${ESPN}/ncaa/500/135.png`,
  "University of Minnesota volleyball": `${ESPN}/ncaa/500/135.png`,
  "Minnesota Gophers": `${ESPN}/ncaa/500/135.png`,
  "Iowa": `${ESPN}/ncaa/500/2294.png`,
  "Iowa Hawkeyes": `${ESPN}/ncaa/500/2294.png`,
  "Wisconsin": `${ESPN}/ncaa/500/275.png`,
  "Wisconsin Badgers": `${ESPN}/ncaa/500/275.png`,
  "Colorado Buffaloes": `${ESPN}/ncaa/500/38.png`,

  // WNBA
  "Minnesota Lynx": "https://a.espncdn.com/i/teamlogos/wnba/500/min.png",

  // MLS
  "Minnesota United": "https://a.espncdn.com/i/teamlogos/soccer/500/144.png",

  // PGA — try ESPN golf CDN; falls back to green badge in component if image 404s
  "PGA": "https://a.espncdn.com/i/teamlogos/golf/500/pgat.png",
  "PGA Tour": "https://a.espncdn.com/i/teamlogos/golf/500/pgat.png",

  // Soccer
  "Manchester City": `${ESPN}/soccer/500/382.png`,
  "Arsenal": `${ESPN}/soccer/500/359.png`,
  "Manchester United": `${ESPN}/soccer/500/360.png`,
  "Liverpool": `${ESPN}/soccer/500/364.png`,
  "Chelsea": `${ESPN}/soccer/500/363.png`,
  "Tottenham Hotspur": `${ESPN}/soccer/500/367.png`,
};

export function getTeamLogo(teamName: string | null | undefined): string | undefined {
  if (!teamName) return undefined;
  if (teamLogoMap[teamName]) return teamLogoMap[teamName];
  // Partial match on last word (e.g. "Vikings", "Twins")
  const lastWord = teamName.trim().split(/\s+/).at(-1)?.toLowerCase();
  if (!lastWord) return undefined;
  for (const [key, url] of Object.entries(teamLogoMap)) {
    if (key.toLowerCase().split(/\s+/).at(-1) === lastWord) return url;
  }
  return undefined;
}
